language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python tests.py
  - python manage.py coverage
branches:
  only:
    - master
after_success:
  coveralls
